### ISSUE TITLE
Italic Variant

### ISSUE THREAD

**Issue by msrumon** [mitradranirban/fonts-mukti#1]
Sir, if you can add an italic version of this font (as well as of other fonts if this variant is missing), we can use it optimally where italic texts need to be displayed.

**Comment by mitradranirban** [comment]
I have plan to come out with italicised form of Mukti in future. Meanwhile you can use my [Ani font]{https://freebangfont.nongnu.org/downloads.html#ani} for a Bangla font with italicised design

**Comment by mitradranirban** [comment]
As per your request, Italic and BoldItalic verson of the font is prepared in version 3.1.0. Please download and use the latest version

**Comment by msrumon** [comment]
Thank you, sir. Really appreciate it.
